spring:
  application:
    name: loan-analytics-service

  config:
    import: "optional:configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-service

  datasource:
    url: jdbc:postgresql://localhost:5432/microbank
    hikari:
      driver-class-name: org.postgresql.Driver
    username: postgres
    password: ${POSTGRES_PASS}
server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      access: read_only