server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Sriharsha6902/myconfigsformicrobankingapp.git
          username: Sriharsha6902
          default-label: main
          password: ${PAT}
  security:
    user:
      name: admin
      password: harsha123
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      access: read_only