spring:
  mail:
    username: sriharshaprathapa@gmail.com
    password: vgcllanhbqntytcm
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          starttls:
            enable: true
            required: true
          timeout: 5000
          writetimeout: 5000
  application:
    name: notification-service

  config:
    import: "optional:configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-service

  datasource:
    url: jdbc:postgresql://localhost:5432/microbank
    hikari:
      driver-class-name: org.postgresql.Driver
    username: postgres
    password: ${POSTGRES_PASS}
  kafka:
    consumer:
      properties:
        spring.json.trusted.packages: microbank.common
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
server:
  port: 8083

